# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ast_transform` gem.
# Please instead update this file by running `bin/tapioca gem ast_transform`.


# pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:3
module ASTTransform
  class << self
    # pkg:gem/ast_transform#lib/ast_transform.rb:37
    def acronym(acronym); end

    # pkg:gem/ast_transform#lib/ast_transform.rb:33
    def acronyms; end

    # pkg:gem/ast_transform#lib/ast_transform.rb:42
    def install; end

    # pkg:gem/ast_transform#lib/ast_transform.rb:56
    def output_path; end

    # pkg:gem/ast_transform#lib/ast_transform.rb:54
    def output_path=(_arg0); end

    # Parses the given +source+ into the framework's AST vocabulary. The entry point for analysis-only consumers
    # that never emit (see ASTTransform::AbstractAnalysis); transformation pipelines go through Transformer.
    #
    # @param source [String] The input source code.
    # @param file_path [String] The file path recorded on source locations.
    #
    # @return [Parser::AST::Node] The AST.
    #
    # pkg:gem/ast_transform#lib/ast_transform.rb:20
    def parse(source, file_path: T.unsafe(nil)); end

    # Parses the source in the given +file_path+ (see .parse).
    #
    # @param file_path [String] The input file path.
    #
    # @return [Parser::AST::Node] The AST.
    #
    # pkg:gem/ast_transform#lib/ast_transform.rb:29
    def parse_file(file_path); end

    private

    # pkg:gem/ast_transform#lib/ast_transform.rb:62
    def source_parser; end
  end
end

# Base class for read-only analysis passes: subclass, harvest state in +on_*+ handlers (always call +super+ so
# traversal continues), and expose results through readers. The walk still functionally rebuilds the tree —
# Parser::AST::Processor has no read-only mode — but +run+ discards the rebuilt tree, so handlers never need to
# care what they return.
#
#   class SendCounter < ASTTransform::AbstractAnalysis
#     attr_reader :count
#
#     def initialize
#       @count = 0
#       super
#     end
#
#     def on_send(node)
#       @count += 1
#       super
#     end
#   end
#
#   SendCounter.new.run(ASTTransform.parse(source)).count
#
# pkg:gem/ast_transform#lib/ast_transform/abstract_analysis.rb:26
class ASTTransform::AbstractAnalysis < ::ASTTransform::AbstractProcessor
  # Runs this analysis on +node+, discarding the rebuilt tree.
  # Note: If you want to add one-time setup or result finalization, override this, then call super.
  #
  # @param node [Parser::AST::Node] The node to be analyzed.
  #
  # @return [ASTTransform::AbstractAnalysis] self, so callers can chain result readers off the run.
  #
  # pkg:gem/ast_transform#lib/ast_transform/abstract_analysis.rb:33
  def run(node); end
end

# Shared traversal core for tree passes. Parser::AST::Processor is a rewriting walker — every visit functionally
# rebuilds the tree — so transformation and analysis share one engine and differ only in what they keep:
# AbstractTransformation's +run+ returns the rebuilt tree, AbstractAnalysis's +run+ discards it and returns the
# harvested results. Subclass one of those leaves rather than this class.
#
# pkg:gem/ast_transform#lib/ast_transform/abstract_processor.rb:10
class ASTTransform::AbstractProcessor < ::Parser::AST::Processor
  include ::ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods
  extend ::ASTTransform::TransformationHelper::Methods

  # Thunks are framework-owned IR: descend into the body so passes that don't know about thunks still process the
  # wrapped statements. Without this, Processor's handler_missing default would pass the node through opaquely,
  # hiding the body from every later pass. The token (first child) is not a node and passes through untouched.
  #
  # pkg:gem/ast_transform#lib/ast_transform/abstract_processor.rb:23
  def on_ast_thunk(node); end

  # Used internally by Parser::AST::Processor to process each node. DO NOT OVERRIDE.
  #
  # pkg:gem/ast_transform#lib/ast_transform/abstract_processor.rb:14
  def process(node); end

  private

  # Processes the given +node+.
  # Note: If you want to do processing on each node, override this.
  #
  # @param node [Parser::AST::Node] The node being visited.
  #
  # @return [Parser::AST::Node] The rebuilt node.
  #
  # pkg:gem/ast_transform#lib/ast_transform/abstract_processor.rb:35
  def process_node(node); end
end

# Base class for structural transformations: subclass and write +on_*+ handlers to rewrite a pattern wherever it
# occurs in the tree. This is one of three authoring shapes — pick by how the rewrite site is found:
#
# - Structural (this class): the pattern alone identifies the site, so +on_*+ handlers rewrite it anywhere in
#   the tree.
# - Positional (node builders): a plain object with +run(node) → node+, including only TransformationHelper. The
#   caller owns traversal and applies the builder at a site it already located; the builder never walks. Anything
#   with that duck type composes with Transformer and other passes — deriving from this class is just one way to
#   implement it.
# - Sibling-annotation: the pattern is a marker statement plus its NEXT sibling, matched in +process_node+ where
#   the child list is visible — an +on_*+ handler sees one node, never its siblings, and cannot delete itself
#   from its parent. See ASTTransform::Transformation (the +transform!+ detector) for the canonical example.
#
# For read-only passes that harvest information instead of rewriting, see ASTTransform::AbstractAnalysis.
#
# pkg:gem/ast_transform#lib/ast_transform/abstract_transformation.rb:20
class ASTTransform::AbstractTransformation < ::ASTTransform::AbstractProcessor
  # Runs this transformation on +node+ and returns the rebuilt tree.
  # Note: If you want to add one-time checks to the transformation, override this, then call super.
  #
  # @param node [Parser::AST::Node] The node to be transformed.
  #
  # @return [Parser::AST::Node] The transformed node.
  #
  # pkg:gem/ast_transform#lib/ast_transform/abstract_transformation.rb:27
  def run(node); end
end

# pkg:gem/ast_transform#lib/ast_transform.rb:10
ASTTransform::DEFAULT_OUTPUT_PATH = T.let(T.unsafe(nil), String)

# pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:4
module ASTTransform::InstructionSequence
  class << self
    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:13
    def source_to_transformed_iseq(source, source_path); end

    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:6
    def using_bootsnap_compilation?; end

    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:29
    def write(string, pathname); end

    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:23
    def write_pathname(file_path); end
  end
end

# pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/bootsnap_mixin.rb:9
module ASTTransform::InstructionSequence::BootsnapMixin
  # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/bootsnap_mixin.rb:10
  def input_to_storage(source, source_path); end
end

# pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/mixin.rb:10
module ASTTransform::InstructionSequence::Mixin
  # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/mixin.rb:11
  def load_iseq(source_path); end
end

# Extends the default Prism parser builder to distinguish keyword arguments from hash literals in the AST.
#
# The upstream builder always emits :hash nodes for both `foo(bar: 1)` and `foo({ bar: 1 })`. Unparser uses the
# node type to decide whether to emit braces: :hash gets `{}`, :kwargs does not. Since Ruby 3.0+ treats these as
# semantically different (strict keyword/positional separation), we need the AST to preserve the distinction.
#
# NOTE: parsed nodes deliberately stay plain Parser::AST::Node. Custom node classes exist only for registered
# custom types (see ASTTransform::Node), which are IR and never reach Unparser: AST::Node#eql? compares class, and
# Unparser verifies dynamic-string emission by re-parsing and comparing eql? against the freshly parsed
# (plain-class) node — custom-class nodes of standard types would fail that verification.
#
# pkg:gem/ast_transform#lib/ast_transform/kwargs_builder.rb:16
class ASTTransform::KwargsBuilder < ::Prism::Translation::Parser::Builder
  # pkg:gem/ast_transform#lib/ast_transform/kwargs_builder.rb:17
  def associate(begin_t, pairs, end_t); end
end

# Line-addressed output: text is placed at absolute line numbers, top to bottom, and the cursor never rewinds.
# When a placement's target line is already behind the cursor, the text is packed (`; `) onto the current line
# instead — Ruby lets statements share a physical line, so alignment degrades locally and the next placement
# whose target is still ahead re-anchors. Knows nothing about Ruby structure or ASTs; callers decide WHAT goes
# on WHICH line, the layout owns the pad-or-pack mechanics.
#
# pkg:gem/ast_transform#lib/ast_transform/layout.rb:9
class ASTTransform::Layout
  # pkg:gem/ast_transform#lib/ast_transform/layout.rb:10
  def initialize; end

  # The line number currently being written; the next fresh line would be +cursor + 1+.
  #
  # pkg:gem/ast_transform#lib/ast_transform/layout.rb:15
  def cursor; end

  # Appends +text+ to the current line with a `; ` separator. The last line is never blank here: padding blanks
  # are only created inside +place+, which immediately overwrites the padded line.
  #
  # pkg:gem/ast_transform#lib/ast_transform/layout.rb:45
  def pack(text); end

  # Places +text+ at +target_line+ when the cursor hasn't passed it; otherwise packs onto the current line.
  # Multi-line text advances the cursor by its height. When opening a fresh line, the first line is indented to
  # +column+ — cosmetic only (leading whitespace is never significant in emitted code), but it keeps the artifact
  # visually close to the source. Packed text ignores the column, as do continuation lines (they keep their own
  # relative indentation).
  #
  # pkg:gem/ast_transform#lib/ast_transform/layout.rb:24
  def place(target_line, text, column: T.unsafe(nil)); end

  # Appends +text+ on a new line unconditionally — for text that must never be `;`-packed after a statement
  # (e.g. keywords).
  #
  # pkg:gem/ast_transform#lib/ast_transform/layout.rb:39
  def place_on_fresh_line(text); end

  # @return [String] the laid-out text, with a trailing newline.
  #
  # pkg:gem/ast_transform#lib/ast_transform/layout.rb:54
  def to_source; end

  private

  # pkg:gem/ast_transform#lib/ast_transform/layout.rb:60
  def indented(text, column); end
end

# Emits a transformed AST as text in which every loc-carrying statement occupies its original source line, so that
# backtraces, breakpoints and debugger display are correct by construction — CRuby derives line numbers from
# physical text position, so placement is our line table.
#
# Placement policy over statement sequences:
#
# 1. Statement has loc: target its source line — the Layout pads to reach it, or packs (`; `) when the cursor has
#    already passed it. A user statement packing means the transform moved it — the alignment auditor's concern,
#    not a runtime failure.
# 2. No loc: pack onto the current line — synthetic code has no source-line truth to preserve.
#
# The emitter owns the Ruby knowledge: walking statement structure, deciding which line each node targets, and
# that keywords can never be `;`-packed. The pad-or-pack mechanics live in Layout; statement-to-text rendering
# (and its isolation workarounds) in StatementRenderer — both created per emission, so the emitter itself is
# stateless and an instance is a reusable collaborator.
#
# Thunk nodes are lowered (ThunkLowering) before layout; the emitter's postcondition is that no custom node type
# (ast_* markers or types registered on ASTTransform::Node) crosses the unparse boundary — they are IR between
# stages that understand them.
#
# pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:28
class ASTTransform::LineAlignedEmitter
  # @param thunk_lowering [ThunkLowering] the lowering run ahead of emission.
  #
  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:45
  def initialize(thunk_lowering: T.unsafe(nil)); end

  # @param ast [Parser::AST::Node] transformed AST
  # @param source_path [String] original file path (for error messages)
  # @return [String] transformed source, line-aligned
  # @raise [ThunkLowering::PlacementError] if a thunk cannot be textually placed
  # @raise [UnloweredNodeTypeError] if a custom node type survived to emission
  #
  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:54
  def emit(ast, source_path); end

  private

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:212
  def assert_no_custom_types(node, source_path); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:139
  def block_assignment?(node); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:196
  def closer_column(node); end

  # The line the container's `end`/`}` occupies in the source, when known.
  #
  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:191
  def closer_line(node); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:182
  def container_body(node); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:153
  def container_delimiters(node, renderer); end

  # Emits a container body that may be a bare :ensure/:rescue node (their begin/end context comes from the
  # surrounding def/block/kwbegin, so the keywords must be emitted inline, aligned like statements).
  #
  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:80
  def emit_body(body, layout, renderer); end

  # Renders a container's opener and closer from the node with its body emptied, then recurses into the body so
  # nested statements align.
  #
  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:146
  def emit_container(node, layout, renderer); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:88
  def emit_ensure(node, layout, renderer); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:106
  def emit_resbody(node, layout, renderer); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:95
  def emit_rescue(node, layout, renderer); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:70
  def emit_statement(node, layout, renderer); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:66
  def emit_statements(statements, layout, renderer); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:167
  def empty_container(node); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:130
  def keyword_column(node); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:125
  def keyword_line(node); end

  # Keywords (rescue/ensure/else) cannot be `;`-packed after a statement; when their line is taken they go on a
  # fresh line instead.
  #
  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:117
  def place_keyword(layout, target_line, keyword, column: T.unsafe(nil)); end

  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:135
  def recursive_container?(node); end

  # Loc-less :begin nodes in statement position (e.g. a lowered thunk in a single-statement container body, carried
  # with its placement) are grouping, not structure: flatten them so each inner statement is laid out independently.
  #
  # pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:203
  def statements_of(body); end
end

# Assignments whose value is a block (e.g. the lowered thunk proc) recurse into the block so its body statements
# align.
#
# pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:41
ASTTransform::LineAlignedEmitter::ASSIGNMENT_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:42
ASTTransform::LineAlignedEmitter::BLOCK_VALUE_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:36
ASTTransform::LineAlignedEmitter::BODY_INDEXES = T.let(T.unsafe(nil), Hash)

# Containers the emitter recurses into so nested statements align; every other node renders as an Unparser blob
# at its head line.
#
# pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:35
ASTTransform::LineAlignedEmitter::RECURSIVE_CONTAINER_TYPES = T.let(T.unsafe(nil), Array)

# Raised as the emitter's postcondition when a custom node type (ast_* markers or types registered on
# ASTTransform::Node) reaches the unparse boundary instead of being lowered by the stage that understands it.
#
# pkg:gem/ast_transform#lib/ast_transform/line_aligned_emitter.rb:31
class ASTTransform::LineAlignedEmitter::UnloweredNodeTypeError < ::StandardError; end

# pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/mixin_utils.rb:4
module ASTTransform::MixinUtils
  class << self
    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/mixin_utils.rb:6
    def try_super(target, method_sym, *args, &block); end
  end
end

# Base class for custom IR nodes. Transform authors subclass it and register a custom node type to get type-routed
# construction from +s+ with domain accessors:
#
#   class InteractionNode < ASTTransform::Node
#     register :rspock_interaction
#
#     def cardinality = children[0]
#   end
#
#   s(:rspock_interaction, ...) # => InteractionNode
#
# Custom node *types* are IR between stages that understand them and must be lowered before emission (the emitter
# enforces this). Standard-typed nodes deliberately stay plain Parser::AST::Node everywhere — parsed and +s+-built
# alike: AST::Node#eql? compares class, and Unparser verifies dynamic-string emission by re-parsing and
# eql?-comparing, so a custom class on a standard type breaks emission.
#
# pkg:gem/ast_transform#lib/ast_transform/node.rb:21
class ASTTransform::Node < ::Parser::AST::Node
  class << self
    # Builds a node of +type+: registered types construct their custom class, everything else a plain
    # Parser::AST::Node.
    #
    # @param type [Symbol] node type
    # @param children [Array] child nodes / literals
    # @param properties [Hash] node properties (e.g. location:)
    # @return [Parser::AST::Node]
    #
    # pkg:gem/ast_transform#lib/ast_transform/node.rb:38
    def build(type, children, properties = T.unsafe(nil)); end

    # Registers +self+ as the class to construct for +type+ nodes.
    #
    # @param type [Symbol] the custom node type routed to this class
    # @return [void]
    #
    # pkg:gem/ast_transform#lib/ast_transform/node.rb:27
    def register(type); end

    # pkg:gem/ast_transform#lib/ast_transform/node.rb:43
    def registry; end
  end
end

# Owns source → AST parsing: Prism's C parser through its whitequark translation layer, so every consumer gets the
# node vocabulary Parser::AST::Processor understands. Transformer parses through this seam, and ASTTransform.parse
# exposes it to analysis-only consumers that never emit.
#
# pkg:gem/ast_transform#lib/ast_transform/source_parser.rb:11
class ASTTransform::SourceParser
  # Parses the given +source+.
  #
  # @param source [String] The input source code.
  # @param file_path [String] The file path recorded on source locations. This is important for source mapping
  # in backtraces.
  #
  # @return [Parser::AST::Node] The AST.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_parser.rb:19
  def parse(source, file_path: T.unsafe(nil)); end

  # Parses the source in the given +file_path+.
  #
  # @param file_path [String] The input file path.
  #
  # @return [Parser::AST::Node] The AST.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_parser.rb:29
  def parse_file(file_path); end

  private

  # Builds a source buffer over +source+ in the parser's default encoding.
  #
  # @param source [String] The input source code.
  # @param file_path [String] The file path recorded on the buffer.
  #
  # @return [Parser::Source::Buffer] The buffer.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_parser.rb:41
  def create_buffer(source, file_path); end

  # The memoized parser, reset between parses.
  #
  # @return [Prism::Translation::Parser] The parser.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_parser.rb:51
  def parser; end
end

# Renders individual statements to text via Unparser, working around the two consequences of unparsing them in
# isolation (line-aligned emission places each statement independently, so each is ripped out of its context):
#
# * Isolation loses the surrounding scope's local variables, making Unparser re-parse identifiers as method calls
#   and fail its dstr round-trip verification — so a renderer is built once per tree with every local bound
#   anywhere in it, and feeds Unparser that set on each render.
# * Unparser normalizes some single-line constructs into multi-line form, which would push following statements
#   off their lines — so renders taller than their source are compressed back to one line when safely possible.
#
# Immutable: configured with the tree's locals at construction, no per-render state.
#
# pkg:gem/ast_transform#lib/ast_transform/statement_renderer.rb:16
class ASTTransform::StatementRenderer
  # @param local_variables [Set<Symbol>] every local bound in the tree the statements come from.
  #
  # pkg:gem/ast_transform#lib/ast_transform/statement_renderer.rb:40
  def initialize(local_variables:); end

  # Renders +node+ no taller than its source when safely possible. Unparser normalizes some single-line
  # constructs into multi-line form (e.g. modifier-if into if/end); when the render is taller than the
  # statement's source, compress it back to one line — verified by re-parse so a statement that cannot be safely
  # single-lined (e.g. containing a heredoc) falls back to its multi-line render.
  #
  # pkg:gem/ast_transform#lib/ast_transform/statement_renderer.rb:54
  def aligned_render(node); end

  # @param node [Parser::AST::Node] the statement to render.
  # @return [String] Unparser's render, informed of the tree's locals.
  #
  # pkg:gem/ast_transform#lib/ast_transform/statement_renderer.rb:46
  def unparse(node); end

  private

  # pkg:gem/ast_transform#lib/ast_transform/statement_renderer.rb:67
  def compress_to_single_line(render); end

  class << self
    # Builds a renderer for statements of +node+'s tree, holding every local bound anywhere in it — an
    # over-approximation that is safe because the set only informs Unparser's re-parse verification, never the
    # rendered text.
    #
    # pkg:gem/ast_transform#lib/ast_transform/statement_renderer.rb:24
    def for_tree(node); end

    private

    # pkg:gem/ast_transform#lib/ast_transform/statement_renderer.rb:30
    def collect_local_variables(node, names = T.unsafe(nil)); end
  end
end

# Node types that bind a local variable name: assignments plus every method/block parameter flavor.
#
# pkg:gem/ast_transform#lib/ast_transform/statement_renderer.rb:18
ASTTransform::StatementRenderer::LOCAL_BINDING_TYPES = T.let(T.unsafe(nil), Array)

# The reordering primitive: an eagerly built wrapper node, spliced wherever the wrapped statements must EXECUTE —
# statement position or composed inside an expression (e.g. an assert_raises block body). Its body keeps its own
# source locations, and the lowering derives the wrapper's textual placement from them (see ThunkLowering), so the
# statements still emit on their original lines even though execution waits.
#
# Children are +[id, *body_statements]+ and the invariants are enforced here in +initialize+, which every
# construction path shares — +s+ routing, the +thunk+ helper, and Processor rebuilds (+updated+ re-initializes).
# Build thunks with +TransformationHelper#thunk+; reuse the same node to execute one body from several points
# (multiplexing).
#
# Runtime semantics are near-transparent (proc lowering): +return+ still returns from the enclosing method, and
# locals the body assigns stay method-scope. See ThunkLowering for the full contract.
#
# pkg:gem/ast_transform#lib/ast_transform/thunk.rb:18
class ASTTransform::Thunk < ::ASTTransform::Node
  # pkg:gem/ast_transform#lib/ast_transform/thunk.rb:28
  def initialize(type, children, properties = T.unsafe(nil)); end

  # Retrieves the Thunk's body.
  #
  # @note Same as the +Parser::AST::Node#children+
  # @return [Array<Parser::AST::Node>] The nodes forming the body of the Thunk.
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk.rb:53
  def body; end

  # Retrieves the Thunk's id.
  # @return [ASTTransform::Thunk::Id] The Id.
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk.rb:47
  def id; end
end

# The identity of a Thunk across transformation passes: Processor and Node#updated rebuilds create new node
# objects, so node identity does not survive — but children DO (carried by reference through every rebuild). Every
# rebuild of a thunk therefore carries this same id object, and the lowering groups occurrences by its object
# identity: one proc, one call per occurrence. Minted internally by the +thunk+ helper, never handled by authors.
# No behavior — a named class over a bare Object.new only for self-documenting AST dumps and greppability.
#
# pkg:gem/ast_transform#lib/ast_transform/thunk.rb:26
class ASTTransform::Thunk::Id; end

# Lowers Thunk nodes into plain Ruby ahead of emission. Each unique thunk (grouped by id identity) becomes a
# hidden proc; each occurrence becomes the proc's call:
#
#   thunk placed at the execution point
#     => x = x; __ast_thunk_<n>__ = proc { body }   (at the body's source lines)
#        ...
#        __ast_thunk_<n>__.call                     (at the occurrence)
#
# Placement is inferred, not authored: the proc's text is inserted into the statement sequence enclosing the
# occurrence, positioned among its siblings by the body's first source line — the lines the author removed the
# statements from. A loc-less body has no textual home and packs immediately before its call. Placements never
# escape a scope boundary (def/class/module bodies absorb their own), because the hidden lvar must share the call's
# method activation; they DO escape block literals, which close over the defining scope.
#
# The closure is a non-lambda proc on purpose: `return` inside a proc returns from the method where the proc was
# defined, and placement and execution always share one method activation, so a thunked `return` keeps its original
# meaning. Jump keywords whose owner lies outside the body keep Ruby's native behavior (`break`/`retry` fail loudly,
# `next`/`redo` silently alter flow) — what a transform chooses to thunk is the transform author's call.
#
# The `x = x` pre-declarations cover every local the body assigns at method scope. A local first assigned inside a
# block literal is block-local, so without a textual method-scope assignment before the proc, thunked assignments
# would be invisible to the statements that read them after the execution point. Self-assignment registers the name
# (nil until the thunk runs — exactly what an unexecuted assignment yields) without clobbering an already-assigned
# value.
#
# Stateless: the thunks encountered during one lowering are tracked in a Registry created at +lower+ entry, so an
# instance is a reusable collaborator.
#
# pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:35
class ASTTransform::ThunkLowering
  include ::ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods
  extend ::ASTTransform::TransformationHelper::Methods

  # @param node [Parser::AST::Node] tree possibly containing Thunk nodes
  # @return [Parser::AST::Node] tree with thunks lowered to plain Ruby
  # @raise [PlacementError] when a thunk body's source lines fall after its execution point, or occurrences of
  #   one thunk diverge
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:93
  def lower(node); end

  private

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:194
  def body_first_line(body); end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:183
  def call_node(id, registry); end

  # The proc's text must precede its call: a placement whose body lines fall at or after the executing statement
  # (or any statement after it) cannot be laid out — the assignment would complete after the call.
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:200
  def check_placement_precedes_execution!(placement, executing_statement, following_statements); end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:214
  def insertion_index(statements, placement); end

  # Lowers a node standing in statement-body position (a container's body or the root), absorbing any placements
  # that arise within it.
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:101
  def lower_body(node, registry); end

  # Lowers a node in expression position. Returns the lowered node and the placements that must be inserted into
  # the enclosing statement sequence.
  #
  # @return [Array(Parser::AST::Node, Array<Placement>)]
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:132
  def lower_expression(node, registry); end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:150
  def lower_generic(node, registry); end

  # Lowers a statement sequence, inserting each placement among the statements by the body's source line.
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:113
  def lower_sequence(node, registry); end

  # An occurrence of a thunk: the first occurrence of its id yields the placement; every occurrence yields the
  # call.
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:169
  def lower_thunk(node, registry); end

  # Locals the thunk body assigns at method scope, in first-assignment order (covers masgn/op_asgn targets — they
  # all carry :lvasgn nodes).
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:229
  def method_scope_assignments(node, names = T.unsafe(nil)); end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:187
  def placement_statements(name, lowered_body, registry); end
end

# Block literals: locals first assigned inside them are block-local (the same lexical rule the pre-declarations
# exist to work around), but their callee/arguments evaluate at method scope and are still descended.
#
# pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:225
ASTTransform::ThunkLowering::BLOCK_TYPES = T.let(T.unsafe(nil), Array)

# Node types opening a new local-variable scope: assignments inside them were invisible to the method scope in
# the original source too, so they get no pre-declaration.
#
# pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:222
ASTTransform::ThunkLowering::NEW_SCOPE_TYPES = T.let(T.unsafe(nil), Array)

# A pending proc definition: +line+ is the body's first source line (nil for fully synthetic bodies),
# +statements+ the pre-declarations plus the proc assignment.
#
# pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
class ASTTransform::ThunkLowering::Placement < ::Struct
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
  def line; end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
  def line=(_); end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
  def statements; end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
  def statements=(_); end

  class << self
    # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
    def [](*_arg0); end

    # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
    def inspect; end

    # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
    def keyword_init?; end

    # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
    def members; end

    # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:40
    def new(*_arg0); end
  end
end

# Raised when a thunk cannot be placed: its body's source lines fall after the execution point (the hidden
# proc's text IS its assignment, so a call can never textually precede the body), or two occurrences of the
# same thunk carry diverging bodies.
#
# pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:45
class ASTTransform::ThunkLowering::PlacementError < ::StandardError; end

# The thunks encountered during one lowering, keyed by identity: allocates each thunk's hidden lvar name
# on first occurrence and verifies later occurrences carry the same body.
#
# pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:49
class ASTTransform::ThunkLowering::Registry
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:50
  def initialize; end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:78
  def hidden_names; end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:55
  def known?(id); end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:67
  def name_for(id); end

  # @return [Symbol] the hidden lvar name allocated for +id+.
  #
  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:60
  def register(id, body); end

  # pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:71
  def verify_same_body!(id, body); end
end

# Scope-opening containers: the hidden lvar cannot be referenced across these boundaries, so placements arising
# inside must land inside.
#
# pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:87
ASTTransform::ThunkLowering::SCOPE_BODY_INDEXES = T.let(T.unsafe(nil), Hash)

# pkg:gem/ast_transform#lib/ast_transform/thunk_lowering.rb:84
ASTTransform::ThunkLowering::SEQUENCE_TYPES = T.let(T.unsafe(nil), Array)

# The +transform!+ detector — the canonical sibling-annotation pass (see AbstractTransformation for the taxonomy).
# A +transform!(...)+ statement is a pragma on the NEXT sibling: the transformations it names are applied to the
# following class definition or constant assignment, and the marker itself is deleted from the child list. Both
# effects need the parent's child list in view, which is why matching happens in +process_node+ — an +on_send+
# handler would see the marker node alone, with no access to its next sibling and no way to remove itself.
#
# pkg:gem/ast_transform#lib/ast_transform/transformation.rb:14
class ASTTransform::Transformation < ::ASTTransform::AbstractTransformation
  private

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:75
  def extract_transformation(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:69
  def extract_transformations(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:44
  def next_child(node, index); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:40
  def previous_child(node, index); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:19
  def process_node(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:48
  def process_node_helper(node, previous_node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:100
  def require_path(const_name); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:87
  def require_transformation(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:57
  def transform_node?(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:63
  def transformable_node?(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:114
  def try_const_get(const_name); end
end

# pkg:gem/ast_transform#lib/ast_transform/transformation.rb:15
ASTTransform::Transformation::TRANSFORM_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# The transform-authoring layer. Three shapes:
#
# - Constructors (+s+, +s_at+): type + children in, fresh node out.
# - The sequence combinator (+run_after+): sequence in, sequence out — the paved road for execution reordering.
# - The low-level reordering primitive (+thunk+): statements in, Thunk node out — for execution points inside
#   expressions.
#
# The contract these helpers serve: textual order is source order. The emitter places every loc-carrying statement
# at its source line; when execution order must differ from textual order, authors express it as a thunk instead of
# moving text.
#
# pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:18
module ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods

  mixes_in_class_methods ::ASTTransform::TransformationHelper::Methods

  class << self
    # pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:23
    def included(base); end
  end
end

# pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:29
module ASTTransform::TransformationHelper::Methods
  # The paved road for execution reordering in flat statement sequences. Named for the constraint, not the
  # mechanism — with text pinned to source lines the only physical lever is delaying execution, so "run X after
  # Y" is the constraint an author states. Returns a NEW sequence in which the +run+ statements are removed and a
  # thunk wrapping them is inserted immediately after +after+.
  #
  # All membership checks are by identity (equal?), never ==: node equality ignores location, so two textually
  # identical statements on different lines compare == and value matching could splice the wrong one.
  #
  # @param statements [Array<Parser::AST::Node>] the sequence being composed
  # @param run [Array<Parser::AST::Node>] contiguous run of elements of +statements+ (by identity) whose
  #   execution must wait
  # @param after [Parser::AST::Node] element of +statements+ (by identity, not inside +run+) the +run+ statements
  #   execute after
  # @return [Array<Parser::AST::Node>] new sequence with the thunk placed
  # @raise [ArgumentError] if +run+ is not a contiguous identity-run of +statements+, or +after+ is not an
  #   element (or is inside +run+)
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:95
  def run_after(statements, run:, after:); end

  # Builds a loc-less node. The emitter packs loc-less nodes onto the current output line — the correct default
  # for synthetic code, which has no source-line truth to preserve.
  #
  # @param type [Symbol] node type
  # @param children [Array] child nodes / literals
  # @param properties [Hash] node properties (e.g. location:)
  # @return [ASTTransform::Node] node routed to its registered class
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:37
  def s(type, *children, **properties); end

  # Builds a fresh node anchored to another node's source location. Use when composing a replacement tree whose
  # root isn't derived from the node it replaces (otherwise prefer +anchor.updated(...)+). The attached map is a
  # clean expression-only Source::Map over +anchor.loc.expression+ — no stale typed sub-ranges (selector etc.).
  # Anchor inheritance is shallow; children keep or lack their own locs.
  #
  # @param anchor [Parser::AST::Node] node whose line this code replaces
  # @param type [Symbol] node type
  # @param children [Array] child nodes / literals
  # @return [ASTTransform::Node] node carrying anchor's expression range
  # @raise [MissingLocationError] if anchor has no expression location
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:51
  def s_at(anchor, type, *children); end

  # The low-level reordering primitive. Thunking is the one reordering lever: text never moves and execution can
  # only move later, so "hoist A above B" is expressed as "run B after A". Returns a single Thunk node: splice it
  # where the statements must RUN — statement position or composed inside an expression, e.g. as an assert_raises
  # block body. The wrapped statements keep their own locs, and the lowering derives the hidden proc's textual
  # placement from them, so the body still emits on its source lines even though execution waits. Reuse the same
  # node to execute one body from several points.
  #
  # Semantics are near-transparent (see ThunkLowering): +return+ still returns from the enclosing method
  # (non-lambda proc), and locals the wrapped statements assign stay method-scope (pre-declared before the proc).
  # Jump keywords whose owner lies outside the wrapped statements keep Ruby's native behavior — +break+/+retry+
  # fail loudly at the jump's own source line, +next+/+redo+ silently end or restart the thunk body. Weigh that
  # when choosing what your surface thunks.
  #
  # Prefer +run_after+ when the execution point sits in the same statement sequence as the statements.
  #
  # @param statements [Array<Parser::AST::Node>] statements to wrap
  # @return [ASTTransform::Thunk] the thunk node
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:75
  def thunk(*statements); end

  private

  # The range +members+ occupies in +sequence+, or nil unless members is a non-empty contiguous identity-run in
  # order.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:114
  def contiguous_identity_range(sequence, members); end
end

# Raised by authoring helpers (e.g. +s_at+) when a node that must carry a source location does not have one.
#
# pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:20
class ASTTransform::TransformationHelper::MissingLocationError < ::StandardError; end

# pkg:gem/ast_transform#lib/ast_transform/transformer.rb:7
class ASTTransform::Transformer
  # Constructs a new Transformer instance.
  #
  # @param transformations [Array<ASTTransform::AbstractTransformation>] The transformations to be run.
  # @param emitter [ASTTransform::LineAlignedEmitter] The emitter rendering transformed ASTs back to source.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:12
  def initialize(*transformations, emitter: T.unsafe(nil)); end

  # Builds the AST for the given +source+.
  #
  # @param source [String] The input source code.
  # @param file_path [String] The file_path. This is important for source mapping in backtraces.
  #
  # @return [Parser::AST::Node] The AST.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:24
  def build_ast(source, file_path: T.unsafe(nil)); end

  # Builds the AST for the given +file_path+.
  #
  # @param file_path [String] The input file path.
  #
  # @return [Parser::AST::Node] The AST.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:33
  def build_ast_from_file(file_path); end

  # Transforms the given +source+.
  #
  # @param source [String] The input source code to be transformed.
  #
  # @return [String] The transformed code, line-aligned (see #transform_file_source).
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:42
  def transform(source); end

  # Transforms the given +ast+.
  #
  # @param ast [Parser::AST::Node] The input AST to be transformed.
  #
  # @return [Parser::AST::Node] The transformed AST.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:83
  def transform_ast(ast); end

  # Transforms the give +file_path+.
  #
  # @param file_path [String] The input file to be transformed. Statement placement (and therefore
  # backtrace and breakpoint line numbers) is derived from this file's source locations.
  # @param transformed_file_path [String] The file path to the transformed file.
  #
  # @return [String] The transformed code.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:55
  def transform_file(file_path, transformed_file_path); end

  # Transforms the given +source+ in +file_path+.
  #
  # @param source [String] The input source code to be transformed.
  # @param file_path [String] The file path for the input +source+. Statement placement (and
  # therefore backtrace and breakpoint line numbers) is derived from the source locations parsed
  # under this path.
  # @param transformed_file_path [String] The file path the transformed file will be written to.
  #
  # @return [String] The transformed code, line-aligned: every statement carrying a source
  # location is emitted at its original source line.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:70
  def transform_file_source(source, file_path, _transformed_file_path); end
end

# pkg:gem/ast_transform#lib/ast_transform/version.rb:4
ASTTransform::VERSION = T.let(T.unsafe(nil), String)
