# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Dev::Deps; end
module SimpleCov::Sorbet::IgnoredRangesTest::Where; end
module SimpleCov::Sorbet::SourceFileIntegrationTest::Cleanup; end
